### ISSUE TITLE
Emscripten WebGPU backend

### ISSUE THREAD

**Issue by maierfelix** [kainino0x/webgpu-cross-platform-demo#1]
Hey there, I'd like to know if the emscripten WebGPU backend could be made public (or ist it already?)

For example: `emscripten_webgpu_get_device`

**Comment by maierfelix** [comment]
Nevermind, found it on your fork: https://github.com/kainino0x/emscripten

**Comment by kainino0x** [comment]
It doesn't work yet; I've only implemented a few entry points. Still working on it!

Also, dawn.h will change to webgpu.h, which will have 2 implementations in native, eventually.
