### ISSUE TITLE
Don't show anything on Edge dev browser

### ISSUE THREAD

**Issue by FuXiii** [kainino0x/webgpu-cross-platform-demo#13]
I use the dev version of Edge browser and on the `WebGPU` flag:
![image](https://user-images.githubusercontent.com/40132375/209435109-58dcedba-6420-4cab-bbee-d22c08b140fb.png)

first `clone` this project and follow the `README Web build` guide
After that I got output files:
![image](https://user-images.githubusercontent.com/40132375/209434863-e6175902-3beb-4965-85f9-b11a9794019c.png)

and then open `hello.html` in `Edge` browser and the information in `console`:
![image](https://user-images.githubusercontent.com/40132375/209434985-7af9211b-2162-4c9d-b77e-0089b080f585.png)

![image](https://user-images.githubusercontent.com/40132375/209435005-62ea4ddf-ac79-4c0e-811b-665027873fed.png)

How to fix this?

**Comment by cwoffenden** [comment]
That's a CORS error, not WebGPU, due to the serving from a `file://` URL. You could either run from a small web server (e.g. `python3 -m http.server`) or add the following to the CMake Emscripten section:
```
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s SINGLE_FILE=1")
```
This will put all of the Wasm and JS into a single file, thus not hitting the CORS error.

**Comment by FuXiii** [comment]
I had tried to use `python3 -m http.server` and visit `http://[::]:8000/` which is the terminal output url
![image](https://user-images.githubusercontent.com/40132375/209439796-0686a9d8-5f85-49fa-9276-bc482c565af1.png)

and then click `hello.html`

![image](https://user-images.githubusercontent.com/40132375/209439895-ef151421-e589-42e1-9642-65ce853e9066.png)

It show `WebGPU not available on this browser...` but the `enable-unsafe-webgpu` flag I had already open it.

(◞‸◟ )

**Comment by cwoffenden** [comment]
Try in the latest Chrome Canary. I don’t know how close the Edge implementation of WebGPU is to the current standard.

**Comment by FuXiii** [comment]
I had installed `Google Chrome Canary` but it still not support `WebGPU`
![image](https://user-images.githubusercontent.com/40132375/209458516-b7e53ab6-abfa-4a31-b77c-394186d969a4.png)

**Comment by cwoffenden** [comment]
Do you see that WebGPU is supported in `chrome://gpu`?

<img width="379" alt="wegbpu" src="https://user-images.githubusercontent.com/8437014/209461868-a2389c93-100b-487c-b3fa-caadbee7a91b.png">

**Comment by FuXiii** [comment]
my:
![image](https://user-images.githubusercontent.com/40132375/209462623-b3532d26-8e3f-4475-8c8c-6329ad0e154b.png)

**Comment by cwoffenden** [comment]
I'm guessing you're not starting Chrome with the `--enable-unsafe-webgpu` flag? On Windows you can right-click on the Chrome shortcut and add it to the launch command after the `.exe` part. On Mac the quickest is to launch from the Terminal with:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-unsafe-webgpu
```
In testing (and I only have a Mac laptop with me for a few days) it looks like Chrome doesn't enable WebGPU without this (it probably needs the origin token). I can take a proper look when I have more than my laptop in the next few days.

**Comment by FuXiii** [comment]
I try to run:
```
C:\Users\g1018\AppData\Local\Google\Chrome SxS\Application>chrome.exe --enable-unsafe-webgpu
```
but it still not support `WebGPU`
〒_〒

Thank you for your patient answer~

**Comment by cwoffenden** [comment]
I built this with the latest Emscripten running on the latest Chrome (not Canary). I enabled WebGPU (in `chrome://flags`) and launched with `--enable-unsafe-webgpu`:

<img width="803" alt="chrome" src="https://user-images.githubusercontent.com/8437014/209464774-56493657-faf4-4c5d-a84f-08fdce82bd6c.png">

I served it with `python3 -m http.server`. I've attached [my build for you to try](https://github.com/kainino0x/webgpu-cross-platform-demo/files/10299763/hello.zip).

Hope that helps!

**Comment by FuXiii** [comment]
Thanks for your help, maybe my computer had been cursed. I gave up, maybe it may succeed in the future

**Comment by FuXiii** [comment]
When I run command `python -m http.server` the terminal output:
```cmd
E:\emsTest\webgpu-cross-platform-demo\build>python -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

I directed visited the `http://[::]:8000/`, after click the `.html` file item in browser, the terminal output `No support for WebGPU; not starting`.

But today I try to visit `http://localhost:8000/`, Bingo~, the triangle comes out~
![image](https://user-images.githubusercontent.com/40132375/209486018-71274e6f-dfbc-47ac-8819-2e69e3f8c227.png)

@cwoffenden Thank you very much for your kind help

⌯'▾'⌯

**Comment by kainino0x** [comment]
Aha, this would be because WebGPU requires a [SecureContext](https://webidl.spec.whatwg.org/#SecureContext). Localhost is a secure context so that you can test things locally, but probably `[::]` isn't on that special local-dev allow-list.

**Comment by cwoffenden** [comment]
Without `--enable-unsafe-webgpu` Chrome doesn't work even on localhost with WebGPU enabled:
<img width="659" alt="WebGPU failing" src="https://user-images.githubusercontent.com/8437014/209784609-ae277402-96cb-447e-b41e-652f1891678b.png">
<img width="759" alt="chrome://flags" src="https://user-images.githubusercontent.com/8437014/209784803-fc4c3457-6970-4f5a-add2-bd54dceaa7a2.png">

**Comment by FuXiii** [comment]
I used `Edge` with `dev` version, I had not set `--enable-unsafe-webgpu` in `Edge`, the `WebGPU` still work well.
![image](https://user-images.githubusercontent.com/40132375/209791232-27537b3d-bfd3-498e-b259-891cec574e57.png)

**Comment by kainino0x** [comment]
> Without `--enable-unsafe-webgpu` Chrome doesn't work even on localhost with WebGPU enabled:

`--enable-unsafe-webgpu` or `chrome://flags/#enable-unsafe-webgpu` is always required for WebGPU even on localhost, UNLESS you have an origin trial for the origin (yes, you can have an origin trial for localhost).
Note `enable-webgpu-developer-features` will not enable-unsafe-webgpu.

Regardless of flags or origin trials, WebGPU always requires a secure context (https or localhost).

**Comment by kainino0x** [comment]
> (e.g. https or localhost)

https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy
