### ISSUE TITLE
iOS/Android demo

### ISSUE THREAD

**Issue by munrocket** [kainino0x/webgpu-cross-platform-demo#16]
I wonder how difficult it can be to create a triangle demo for iOS/Android.

**Comment by munrocket** [comment]
![IMG_1442](https://github.com/kainino0x/webgpu-cross-platform-demo/assets/20033246/7bfda0fa-bec4-471e-8900-26726a6dc7ef)
One can expect official support for Android later and maybe some demos.

**Comment by kainino0x** [comment]
That table is about Chrome WebGPU support - if you're looking for native Dawn sample apps for Android and iOS, they're not planned, though they'd be very useful resources for people!

**Comment by munrocket** [comment]
https://github.com/eliemichel/LearnWebGPU-Code/tree/step030-sdl
