### ISSUE TITLE
build error: ‘WGPUPresentMode’ was not declared in this scope

### ISSUE THREAD

**Issue by coding-001** [kainino0x/webgpu-cross-platform-demo#2]
There was a build error at beginning:
third_party/webgpu_cpp/webgpu/webgpu_cpp.h:4:10: fatal error: webgpu/webgpu.h: No such file or directory
 #include "webgpu/webgpu.h"
changed to:
#include "dawn/webgpu.h"
#include "dawn/EnumClassBitmasks.h"
then I got:
third_party/webgpu_cpp/webgpu/webgpu_cpp.cpp:166:49: error: ‘WGPUPresentMode’ was not declared in this scope
     static_assert(sizeof(PresentMode) == sizeof(WGPUPresentMode), "sizeof mismatch for PresentMode");

**Comment by coding-001** [comment]
os: Ubuntu Server 18.04.1 LTS 64

**Comment by kainino0x** [comment]
sorry, I just broke the native build. You can go back a few revisions but I'm trying to fix this now.

**Comment by kainino0x** [comment]
Should work now. Build instructions have changed a little; see README.
